### ISSUE TITLE
Theme page is missing demo and image.  

### ISSUE THREAD

**Issue by qqhann** [qqhann/hugo-primer#36] opened 2019-11-01 18:46 UTC
https://themes.gohugo.io/hugo-primer/

The demo is missing and the image is invalid.

**Comment by onedrawingperday** [comment] 2019-11-16 22:21
Hello @qqhann 

The demo is missing because it is broken since https://github.com/qqhann/hugo-primer/commit/2a71ad29a82d1394767bf0eac8bedc26db12376a

The problem is [here](https://github.com/qqhann/hugo-primer/blob/a015ab24ae724c2e4b524790a0784b9431b82c54/layouts/index.html#L37)

```
9:43:10 PM:  ==== PROCESSING  hugo-primer  ======
9:43:10 PM: Building site for theme hugo-primer using config "/opt/build/repo/_script/hugoThemeSite/config-hugo-primer.toml" to ../themeSite/static/theme/hugo-primer/
9:43:10 PM: ERROR 2019/11/16 19:43:10 render of "home" failed: "/opt/build/repo/hugo-primer/layouts/index.html:37:22": execute of template failed: template: index.html:37:22: executing "main" at <.RelPermalink>: can't evaluate field RelPermalink in type *page.Pager
9:43:10 PM: Error: Error building site: failed to render pages: render of "home" failed: "/opt/build/repo/hugo-primer/layouts/index.html:37:22": execute of template failed: template: index.html:37:22: executing "main" at <.RelPermalink>: can't evaluate field RelPermalink in type *page.Pager
9:43:10 PM: FAILED to create demo site for hugo-primer
```

I don't see problem with the screenshots.

Once you look into the above let me know so that I can update your theme.

**Comment by qqhann** [comment] 2019-12-02 16:20
Hi @onedrawingperday 

Wow, didn't expect a Hugo maintainer to come see here. It's an honor. :)

And thank you for pointing out the cause.
It seems I could not follow .URL update well in index.md.

Also, I've added exampleSite, so the demo should work better.

Could you see whether it's good now?

**Comment by onedrawingperday** [comment] 2019-12-02 17:10
Hello @qqhann 

The theme demo was fixed by commit https://github.com/qqhann/hugo-primer/commit/4d672b89071f1b858879073034b61f9b5fbe8a97 and currently it already renders fine on the Hugo Themes showcase: https://themes.gohugo.io/hugo-primer/

I just tested your theme with the added exampleSite locally with the Hugo Themes Build Script and I noticed that you have enabled sharing to various social media platforms, over here: https://github.com/qqhann/hugo-primer/blob/master/exampleSite/config.toml#L25

In the Hugo Themes guidelines [we mention](https://github.com/gohugoio/hugoThemes#adding-a-theme-to-the-list) that: 

>An Example Site should not have third party tracking enabled. If you wish to provide configuration parameters to third party services (analytics, comments etc) then please do not enter a valid account ID or username.

So I request that you mention the share widget in your theme's README but disable it from line 25 of the exampleSite config, because the provided share buttons will track users of your theme and that is not acceptable on the Hugo Themes Site.

If you feel like changing the sharing buttons, so that there is no user tracking,  I suggest that you have a look at https://sharingbuttons.io/ for inspiration.

If not then as I said above simply disable these buttons in the config and document their use in the README.

**Comment by qqhann** [comment] 2019-12-02 17:34
My bad, I quick fixed it by disabling share widget on exampleSite.


> If you feel like changing the sharing buttons, so that there is no user tracking, I suggest that you have a look at https://sharingbuttons.io/ for inspiration.

Thanks for letting me know! I'll take in consideration for future updates.

**Closed** 2019-12-11 15:29 UTC
